### ISSUE TITLE
How to use this project to create a rtmp video player?

### ISSUE THREAD

**Issue by tailiu** [xiongziliang/ZLMediaKit#14]
Hi, this is an amazing project with many functions! I have successfully compiled ZLMediaKit on my Linux machine and run the test files, but I am still confused about how to use it as a rtmp video player. Could you please give me some detailed guide about how to run it? Thanks very much!

**Comment by xiongziliang** [comment]
> Hi, this is an amazing project with many functions! I have successfully compiled ZLMediaKit on my Linux machine and run the test files, but I am still confused about how to use it as a rtmp video player. Could you please give me some detailed guide about how to run it? Thanks very much!

The RTMP player on ZLMediaKit  only implements protocol layer,you need to decode frame and display by yourself . You can refer to this code to see how to use it :[https://github.com/xiongziliang/ZLMediaKit/blob/master/tests/test_player.cpp](test_player.cpp)

**Comment by xiongziliang** [comment]
The project of ZLMediaPlayer just only adapted to branch 2.0(or  branch 1.0 perhaps ) of ZLMediaKit，You need to switch the code to the old branch to compile it.

I'm sorry for the confusion and annoyance I've brought you because of my limited energy.

**Comment by tailiu** [comment]
> The project of ZLMediaPlayer just only adapted to branch 2.0(or branch 1.0 perhaps ) of ZLMediaKit，You need to switch the code to the old branch to compile it.
> 
> I'm sorry for the confusion and annoyance I've brought you because of my limited energy.

Thanks for your helpful replies.  I checked out to the branch 2.0 and successfully compiled ZLMediaPlayer. However, after I typed "./test_player rtmp://localhost/live/stream" or "./test_player" to receive a rtmp stream, the program did not print any results. (I can use ffplay to receive the rtmp stream, so I think there is no problem with the rtmp stream.) I am not sure whether I used wrong commands.

**Comment by xiongziliang** [comment]
> > The project of ZLMediaPlayer just only adapted to branch 2.0(or branch 1.0 perhaps ) of ZLMediaKit，You need to switch the code to the old branch to compile it.
> > I'm sorry for the confusion and annoyance I've brought you because of my limited energy.
> 
> Thanks for your helpful replies. I checked out to the branch 2.0 and successfully compiled ZLMediaPlayer. However, after I typed "./test_player rtmp://localhost/live/stream" or "./test_player" to receive a rtmp stream, the program did not print any results. (I can use ffplay to receive the rtmp stream, so I think there is no problem with the rtmp stream.) I am not sure whether I used wrong commands.

Hi friend,  i've found a bug that can't be played, and it's actually fixed in the latest master branch. I just merged the repaired code into branch 2.0. Please pull down the code in branch 2.0 and try again.

I'm sorry for this bug. and thank you for your feedback.

**Comment by tailiu** [comment]
> > > The project of ZLMediaPlayer just only adapted to branch 2.0(or branch 1.0 perhaps ) of ZLMediaKit，You need to switch the code to the old branch to compile it.
> > > I'm sorry for the confusion and annoyance I've brought you because of my limited energy.
> > 
> > 
> > Thanks for your helpful replies. I checked out to the branch 2.0 and successfully compiled ZLMediaPlayer. However, after I typed "./test_player rtmp://localhost/live/stream" or "./test_player" to receive a rtmp stream, the program did not print any results. (I can use ffplay to receive the rtmp stream, so I think there is no problem with the rtmp stream.) I am not sure whether I used wrong commands.
> 
> Hi friend, i've found a bug that can't be played, and it's actually fixed in the latest master branch. I just merged the repaired code into branch 2.0. Please pull down the code in branch 2.0 and try again.
> 
> I'm sorry for this bug. and thank you for your feedback.

Thanks for solving the bug! It can work now, but I find that if I use Ctrl + C to exit ZLMediaPlayer, it shows "Segmentation fault (core dumped)". Also, does ZLMediaPlayer provide any graphical interface for me to view received rtmp streams?

**Comment by xiongziliang** [comment]
I've just fixed all the bugs you mentioned,Please pull down the latest code of ZLMediaPlayer.
This ZLMediaPlayer project is just a player kernel like FFmpeg, it uses SDL to render images and sounds without any other GUI interface.
So what's the graphical user interface you're talking about?

**Comment by tailiu** [comment]
Thanks for fixing the bugs and pointing out SDL. I think I have the graphical user interface question because I cannot see images or sounds of streamed videos. After I run "./test_player rtmp://localhost/live/stream", I only got the following output without any images or sounds. Also, now I cannot use Ctrl + C to exit the program. 

test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.cpp 89
2018-12-18 14:37:15.672 D | play localhost live stream
test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.cpp 307
2018-12-18 14:37:15.715 W | onRtmpChunk can not support cmd:|RtmpSampleAccess
test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpParser.cpp 46
2018-12-18 14:37:15.715 I | RtmpParser 不支持RTMP视频格式:2
test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpParser.cpp 60
2018-12-18 14:37:15.715 I | RtmpParser 不支持RTMP音频格式:2
test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.h 78
2018-12-18 14:37:15.715 W | _onPlayResult 0 play rtmp success
test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.cpp 248
2018-12-18 14:37:15.715 W | onCmd_result unhandled _result
test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp 639
2018-12-18 14:37:15.724 T | handle_rtmpChunk CONTROL_STREAM_BEGIN:1337

**Comment by xiongziliang** [comment]
> Thanks for fixing the bugs and pointing out SDL. I think I have the graphical user interface question because I cannot see images or sounds of streamed videos. After I run "./test_player rtmp://localhost/live/stream", I only got the following output without any images or sounds. Also, now I cannot use Ctrl + C to exit the program.
> 
> test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.cpp 89
> 2018-12-18 14:37:15.672 D | play localhost live stream
> test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.cpp 307
> 2018-12-18 14:37:15.715 W | onRtmpChunk can not support cmd:|RtmpSampleAccess
> test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpParser.cpp 46
> 2018-12-18 14:37:15.715 I | RtmpParser 不支持RTMP视频格式:2
> test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpParser.cpp 60
> 2018-12-18 14:37:15.715 I | RtmpParser 不支持RTMP音频格式:2
> test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.h 78
> 2018-12-18 14:37:15.715 W | _onPlayResult 0 play rtmp success
> test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpPlayer.cpp 248
> 2018-12-18 14:37:15.715 W | onCmd_result unhandled _result
> test_player(19855) /home/nyuad/Downloads/ZLMediaKit/src/Rtmp/RtmpProtocol.cpp 639
> 2018-12-18 14:37:15.724 T | handle_rtmpChunk CONTROL_STREAM_BEGIN:1337

ZLMediaKit currently supports limited protocols and coding formats. It only supports playback of rtsp/rtmp protocols, and the coding formats are limited to h264/h265, aac.

From the log you pasted, ZLMediaKit is unable to decode and display because it does not support that encoding format.

ZLMediaKit is not a universal player, so if you want to support multiple media formats, it is recommended that you use FFmpeg or VLC to develop it.I'm sorry for this.

**Comment by tailiu** [comment]
Hi, I tried h264/h265 coded videos on this link https://www.h265files.com/ and some acc coded audios, but with no luck, the program still showed the same errors (不支持RTMP视频格式:2...). I am using rtmp protocols.

**Comment by xiongziliang** [comment]
Please use the rtmp url:

[rtmp://live.hkstv.hk.lxdns.com/live/hks2](rtmp://live.hkstv.hk.lxdns.com/live/hks2)
[rtmp://live.hkstv.hk.lxdns.com/live/hks1](rtmp://live.hkstv.hk.lxdns.com/live/hks1)

I played it successed:
<img width="759" alt="wx20181220-150847 2x" src="https://user-images.githubusercontent.com/11495632/50269426-2d52f780-0469-11e9-8f76-f75a1224dc0a.png">

**Comment by xiongziliang** [comment]
And I can exit the program by pressing Ctr + C:
![image](https://user-images.githubusercontent.com/11495632/50269549-80c54580-0469-11e9-870a-c21fe9398519.png)

**Comment by tailiu** [comment]
Thanks so much for your prompt replies! I can exit the program with Ctrl + C. I find the reasons why I cannot play the audios and videos. I used a wrong ffmpeg command: ffmpeg -re -i video.mkv -f flv rtmp://localhost/live/stream to publish these videos. This command does not keep the original codec of the audios and videos. Now I use a ffmpeg command: ffmpeg -re -i video.mkv -vcodec copy -acodec copy -f flv rtmp://localhost/live/stream. This command can keep the original codec (h264/265) of both audio and video. Now ZLMediaPlayer can work perfectly!
